// eslint-disable-next-line import/no-anonymous-default-export
export default {
  success: true,
  data: {
    chats: [
      {
        id: "0",
        name: "Andrew Smith",
        image: "assets/images/profiles/andrew.png",
        msg: "Andrew is typing...",
        time: "8:45 AM",
      },
      {
        id: "1",
        name: "Regina",
        image: "assets/images/profiles/regina.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "2",
        name: "Russell",
        image: "assets/images/profiles/russel.png",
        msg: "Andrew is typing...",
        time: "8:45 AM",
      },
      {
        id: "3",
        name: "Audrey Jones",
        image: "assets/images/profiles/audrey.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "4",
        name: "Natasha",
        image: "assets/images/profiles/natasha.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "5",
        name: "Jane Foster",
        image: "assets/images/profiles/jane.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "6",
        name: "Justin",
        image: "assets/images/profiles/justin.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "7",
        name: "Carmon",
        image: "assets/images/profiles/carmon.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
    ],
    groups: [
      {
        id: "0",
        name: "Family",
        image: "assets/images/groups/family.png",
        msg: "Johnnah is typing...",
        time: "8:45 AM",
      },
      {
        id: "1",
        name: "My Team",
        image: "assets/images/groups/team.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "2",
        name: "Friends",
        image: "assets/images/groups/friend.png",
        msg: "Andrew is typing...",
        time: "8:45 AM",
      },
      {
        id: "3",
        name: "office",
        image: "assets/images/groups/company.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "4",
        name: "Project",
        image: "assets/images/groups/project.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "5",
        name: "Coding Challanges",
        image: "assets/images/groups/code.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "6",
        name: "Deals you can't miss!",
        image: "assets/images/groups/deals.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "7  ",
        name: "Jst for fun!",
        image: "assets/images/groups/fun.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "8",
        name: "Family",
        image: "assets/images/groups/family.png",
        msg: "Johnnah is typing...",
        time: "8:45 AM",
      },
      {
        id: "9",
        name: "My Team",
        image: "assets/images/groups/team.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "10",
        name: "Friends",
        image: "assets/images/groups/friend.png",
        msg: "Andrew is typing...",
        time: "8:45 AM",
      },
      {
        id: "11",
        name: "office",
        image: "assets/images/groups/company.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "12",
        name: "Project",
        image: "assets/images/groups/project.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "13",
        name: "Coding Challanges",
        image: "assets/images/groups/code.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "14",
        name: "Deals you can't miss!",
        image: "assets/images/groups/deals.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "15",
        name: "Jst for fun!",
        image: "assets/images/groups/fun.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "16",
        name: "Family",
        image: "assets/images/groups/family.png",
        msg: "Johnnah is typing...",
        time: "8:45 AM",
      },
      {
        id: "17",
        name: "My Team",
        image: "assets/images/groups/team.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "18",
        name: "Friends",
        image: "assets/images/groups/friend.png",
        msg: "Andrew is typing...",
        time: "8:45 AM",
      },
      {
        id: "19",
        name: "office",
        image: "assets/images/groups/company.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "20",
        name: "Project",
        image: "assets/images/groups/project.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "21",
        name: "Coding Challanges",
        image: "assets/images/groups/code.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "22",
        name: "Deals you can't miss!",
        image: "assets/images/groups/deals.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "23",
        name: "Jst for fun!",
        image: "assets/images/groups/fun.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "24",
        name: "Family",
        image: "assets/images/groups/family.png",
        msg: "Johnnah is typing...",
        time: "8:45 AM",
      },
      {
        id: "25",
        name: "My Team",
        image: "assets/images/groups/team.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "26",
        name: "Friends",
        image: "assets/images/groups/friend.png",
        msg: "Andrew is typing...",
        time: "8:45 AM",
      },
      {
        id: "27",
        name: "office",
        image: "assets/images/groups/company.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "28",
        name: "Project",
        image: "assets/images/groups/project.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "29",
        name: "Coding Challanges",
        image: "assets/images/groups/code.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "30",
        name: "Deals you can't miss!",
        image: "assets/images/groups/deals.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "31",
        name: "Jst for fun!",
        image: "assets/images/groups/fun.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "32",
        name: "Family",
        image: "assets/images/groups/family.png",
        msg: "Johnnah is typing...",
        time: "8:45 AM",
      },
      {
        id: "33",
        name: "My Team",
        image: "assets/images/groups/team.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "34",
        name: "Friends",
        image: "assets/images/groups/friend.png",
        msg: "Andrew is typing...",
        time: "8:45 AM",
      },
      {
        id: "35",
        name: "office",
        image: "assets/images/groups/company.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "36",
        name: "Project",
        image: "assets/images/groups/project.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "37",
        name: "Coding Challanges",
        image: "assets/images/groups/code.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "38",
        name: "Deals you can't miss!",
        image: "assets/images/groups/deals.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "39",
        name: "Jst for fun!",
        image: "assets/images/groups/fun.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "40",
        name: "My Team",
        image: "assets/images/groups/team.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
    ],
  },
};
