// eslint-disable-next-line import/no-anonymous-default-export
export default {
  success: true,
  data: {
    chats: [
      {
        id: "1",
        name: "Andrew Smith",
        image: "assets/images/profiles/andrew.png",
        msg: "Andrew is typing...",
        time: "8:45 AM",
      },
      {
        id: "2",
        name: "Regina",
        image: "assets/images/profiles/regina.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "3",
        name: "Russell",
        image: "assets/images/profiles/russel.png",
        msg: "Andrew is typing...",
        time: "8:45 AM",
      },
      {
        id: "4",
        name: "Audrey Jones",
        image: "assets/images/profiles/audrey.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "5",
        name: "Natasha",
        image: "assets/images/profiles/natasha.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "6",
        name: "Jane Foster",
        image: "assets/images/profiles/jane.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "7",
        name: "Justin",
        image: "assets/images/profiles/justin.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "8",
        name: "Carmon",
        image: "assets/images/profiles/carmon.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
    ],
    groups: [
      {
        id: "1",
        name: "Family",
        image: "assets/images/groups/family.png",
        msg: "Johnnah is typing...",
        time: "8:45 AM",
      },
      {
        id: "2",
        name: "My Team",
        image: "assets/images/groups/team.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "3",
        name: "Friends",
        image: "assets/images/groups/friend.png",
        msg: "Andrew is typing...",
        time: "8:45 AM",
      },
      {
        id: "4",
        name: "office",
        image: "assets/images/groups/company.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "5",
        name: "Project",
        image: "assets/images/groups/project.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "6",
        name: "Coding Challanges",
        image: "assets/images/groups/code.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "7",
        name: "Deals you can't miss!",
        image: "assets/images/groups/deals.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
      {
        id: "8",
        name: "Jst for fun!",
        image: "assets/images/groups/fun.png",
        msg: "you can check this out at figma.com",
        time: "8:45 AM",
      },
    ],
  },
};
